config/routes.rb
Forms::Application.routes.draw do

  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  post '/reset_password/new', to: 'reset_password#create', as: 'send_reset_password'
  post '/reset_password', to: 'reset_password#update'

end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    redirect_to root_path, notice: "Email sent with password reset instructions."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.reset_password_sent_at < 2.hours.ago
      redirect_to_new password_reset_path, alert: "Reset password request has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_path, notice: "Password has been reset!"
    else
      render :edit
    end
  end
end

app/views/reset_password/index.html.erb
<div id="container">
	<div class="registerbox">
		<h1 class="register">Your new password</h1>
	</div>
		<div class="form">

		<%= form_for (@user) do |f| %>


    	<div class="field">
      <%= f.password_field :password, placeholder: "Enter new password", class: 'form-input' %>
    </div>
	<div class="actions">
      <%= f.submit "Reset Password", class: "submitbutton" %>
    </div>
 <% end %>

 </div>
</div>

app/views/reset_password/new.html.erb
<div id="container">
	<div class="registerbox">
		<h1 class="register">Reset your password</h1>
	</div>
		<div class="form">

		<%= form_for @user, url: new_reset_password_path do |f| %>


    	<div class="field">
      <%= f.text_field :email, placeholder: "Your email address", class: 'form-input' %>
    </div>
	<div class="actions">
      <%= f.submit "Reset Password", class: "submitbutton" %>
    </div>
 <% end %>

 </div>
</div>