config/routes.rb
Forms::Application.routes.draw do

  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  post '/reset_password/new', to: 'reset_password#create', as: 'send_reset_password'
  post '/reset_password', to: 'reset_password#update'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
								uniqueness: {case_sensitive: false}
	validates :username, presence: true, uniqueness: true, length: {maximum: 50}
	has_secure_password
	validates :password, length: {minimum: 6}
	validates :password_confirmation, presence: true



	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(:id => params[:id])
    if params[:id] =! session[:user_id]
      redirect_to root_url
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        WelcomeMailer.welcome_email(@user).deliver
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation, :birthday, :avatar, :agree)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {size:35})
    gravatar_id = Digest::MD5::hexdigest(User.find_by(params[:id]).email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: User.find_by(params[:id]).name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
  <div class="circle"></div>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'Name', class: 'form-input' %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: 'Email', class: 'form-input' %>
  </div>
  <div class="field">
    <%= f.text_field :username, placeholder: 'Username', class: 'form-input' %>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: 'Password', class: 'form-input' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: 'form-input' %>
  </div>
  <div class="field">
    <%= f.text_field :birthday, placeholder: 'When were you born?', class: 'form-input datepicker' %>
  </div>
  <div class="field">
    <%= f.check_box :agree %>
    <%= f.label :agree, "I agree to the terms of service" %>
  </div>
  <div class="actions">
    <%= f.submit :submit, :value => "Join", class: 'registerbutton' %>
  </div>
<% end %>
<hr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Birthday</th>
      <th>Avatar</th>
      <th>Agree</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.birthday %></td>
        <td><%= user.avatar %></td>
        <td><%= user.agree %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="container">
	<div class="registerbox">
		<h1 class="register">Register</h1>
	</div>
		<div class="form">
			<%= render "form" %>
			
			Already have an account? <%= link_to "Sign in", signin_path %>
	  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @user.avatar %>
</p>

<p>
  <strong>Agree:</strong>
  <%= @user.agree %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>