config/routes.rb
Forms::Application.routes.draw do

  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reset_password

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  post '/reset_password/new', to: 'reset_password#create', as: 'send_reset_password'
  post '/reset_password', to: 'reset_password#update'

end

app/views/layouts/_footer.html.erb
<!-- <footer class="footer">
  <small>
    <a href="http://www.google.com">Google</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer> -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="navbar-inner">
    <div class="container">
    <p class='navbar-brand'><%= link_to 'OurApp', root_path %></p>
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span><%= gravatar_for @user %></span><%= current_user.name.capitalize %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Sign Out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign In", signin_path %></li>
            <li><%= link_to "Register", signup_path %></li>
          <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forms</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,400|Roboto+Slab:400,100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  
  <%= csrf_meta_tags %>
  <script>
  $(function() {
    $( ".datepicker" ).datepicker({
    changeMonth: true,
    changeYear: true,
    yearRange: "-80:+0"
    });
  });
  </script>
</head>
<body>
<%= render 'layouts/header' %>
  <div class="container">	
	<%= yield %>
  <%= render 'layouts/footer' %>
  </div>
</body>
</html>